import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the workflow package and gitignored; it ships its own
    // `/* eslint-disable */`, which then reports as an unused directive.
    "src/app/.well-known/**",
    // A SEPARATE npm project with its own package.json and its own deps. Same
    // reasoning as tsconfig.json's exclude, and the same failure if omitted:
    // rules resolve against dependencies this project does not install.
    "ios-shell/**",
  ]),
  {
    // A leading underscore is this repo's "deliberately unused" marker. It is
    // load-bearing in the e2e suite, where `account: _account` requests a
    // fixture BY NAME for its side effects (it mints and authenticates a temp
    // user) while binding it to something the test body never reads.
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    // The React Compiler rules, kept VISIBLE as warnings rather than silenced,
    // and deliberately not gating.
    //
    // They are worth having: on new code they catch real mistakes, and one of
    // them (`preserve-manual-memoization`) found a genuine bug here - a useMemo
    // whose dependency was spelled `activeWorkout?.exercises` while its body
    // read `activeWorkout.exercises`, which made the compiler give up on the
    // whole component. That one is fixed.
    //
    // The 28 that remain are all the same three deliberate patterns, and every
    // one of them is correct as written:
    //   - reading a browser-only value on MOUNT and setting state from it
    //     (localStorage, isNative(), SpeechRecognition, Notification). Doing it
    //     during render is a hydration mismatch, so the effect is mandatory.
    //   - resetting a dialog's form state when it opens.
    //   - writing `ref.current`, and minting an id with `Date.now()` inside an
    //     event handler.
    // Restructuring those would mean rewriting the rest-timer rehydrate, the
    // tracking-progress restore and the workout editor - the three most
    // delicate things in the app, twice the source of a shipped crash - to
    // satisfy a rule about a React Compiler migration this codebase has not
    // made. That is the wrong trade, so they warn instead of erroring and
    // `npm run lint` can gate on everything else.
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/immutability": "warn",
      "react-hooks/purity": "warn",
      "react-hooks/refs": "warn",
    },
  },
  {
    // Playwright specs are not React. `use` here is the fixture callback from
    // `test.extend`, and the hooks plugin reads the name and assumes React's
    // `use`, reporting a rules-of-hooks violation in a file with no React in
    // it at all.
    files: ["e2e/**/*.ts"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
    },
  },
]);

export default eslintConfig;
